name: CI Pipeline

on: 
  [push,pull_request]

jobs:
  lint:
    name: performs liniting 
    runs-on: ubuntu-latest

    steps:
      - name: fetch repo
        run: actions/checkout@v4

      - name: install shell-check
        run: sudo apt install shellcheck

      - name: run shellcheck
        run: shellcheck linux-sysmonitor/health-check.sh
      



