name: CI Pipeline

on: 
  [ push,pull_request ]

permissions:
  contents: read
  packages: write 

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: fetch repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.4.0

      - name: cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-apt-
      
      - name: install shell-check
        run: sudo apt install shellcheck

      - name: run shellcheck
        run: shellcheck linux-sysmonitor/health-check.sh
  
  test:
    runs-on: ubuntu-24.04
    needs: lint

    steps:
      - name: fetch repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.4.0

      - name: execute health-check.sh
        run: bash linux-sysmonitor/health-check.sh >  health-report-$(date +%Y%m%d-%H%M%S).txt 2>&1

      - name: upload report to artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4
        with:
          name: health-report
          path: health-report-*.txt
          retention-days: 7
  
  build:
    runs-on: ubuntu-24.04
    needs: [ lint, test ]

    steps:
      - name: fetch repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.4.0

      - name: build image 
        uses: docker/build-push-action@v7
        with:
          cache-from: type=gha # try to restore previous cache if exisit
          cache-to: type=gha,mode=max # store current docker build  and max = save all resuable layer unline min 
      
      - name: latest-tag
        if: github.ref == 'refs/heads/main'
        run: docker tag ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }} ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:latest
      
      - name: run docker images
        run: docker images 
      
      - name: ghcr login 
        uses: docker/login-action@v3 
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}} # automatically picked
      
      - name: push sha-tagged image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }}
      
      - name: push latest image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:latest

      - name: pull docker image
        run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }}
  
  scan:
    runs-on: ubuntu-24.04
    needs: build

    permissions:
      security-events: write
    
    steps:
      - name: ghcr login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: pull docker image 
        run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }}
      
      - name: aquasecurity scan 
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }}
          # exit-code: 1 # TODO: Re-enable `exit-code: 1` after fixing CRITICAL vulnerabilities.
          severity: CRITICAL
      
      - name: generate trivy sarif report
        # if: always() - TODO: uncomment when exit-code:1 is enabled 
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          skip-setup-trivy: true
          image-ref: ${{ env.REGISTRY }}/${{ github.repository }}/linux-sysmonitor:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
      
      - name: sarif upload
        # if: always() - TODO: uncomment when exit-code:1 is enabled
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: trivy-scan-analysis
