name: docker build and push

on: 
  workflow_call:
    inputs:
      image-tag: 
        required: true
        type: string 

      push:
        default: false
        type: boolean 
      
    secrets:
      REGISTRY_TOKEN:
        required: true 
      

